### ISSUE TITLE
[Feature]: Uploading auto deletes local file

### ISSUE THREAD

**Issue by vanbang9710** [Kuingsmile/PicList#40]
### 前置阅读 | Pre-reading

- [X] [文档/Doc](https://picgo.github.io/PicGo-Doc/)
- [X] [Issues](https://github.com/Kuingsmile/PicList/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Kuingsmile/PicList/blob/dev/FAQ.md)

### PicList的版本 | PicList Version

1.7.0

### 系统信息 | System Information

Windows

### 功能请求 | Feature request

The plugin "auto-delete" seems to not work with piclist. And even with PicGo, in Obsidian, when using the command "Image auto upload Plugin: Upload all images", it only deletes the 1st image

**Comment by Kuingsmile** [comment]
Hi, @vanbang9710 , thanks for your support.

Regarding the first question, it is worth noting that the "auto-delete" plugin can work with PicList. However, when you enable PicList's built-in watermark or picture processing module, the input changes from raw files to processed temp files in the "piclistTemp" directory. As a result, the "auto-delete" plugin will delete the temp file instead of the raw file. 

![image](https://user-images.githubusercontent.com/96409857/232645981-07e452c6-1820-4aff-9b9e-ee7388b49b86.png)

As for the second question, the issue you encountered with the Obsidian command "Image auto-upload Plugin: Upload all images" deleting only the first image is caused by the "auto-delete" plugin. Upon reading its source code, it is clear that the plugin gets the file to be deleted using the line file = input[0], which results in only the first image being deleted.

![image](https://user-images.githubusercontent.com/96409857/232646182-60e415cd-023b-4acb-9032-b74e1c4ca939.png)

As the implementation of the "auto-delete" plugin is quite straightforward, I will embedding it in the next version of PicList. This will also resolve any conflicts between the "auto-delete" plugin and the picture processing module in PicList.
